### ISSUE TITLE
Issue with sqlite3

### ISSUE THREAD

**Issue by jeweua** [RealityNet/teleparser#8]
python3 teleparser.py ../cache4.db ../

```
Traceback (most recent call last):
  File "teleparser.py", line 47, in <module>
    import sqlite3
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'
```

however, sqlite3 is installed. Any ideas?

Does it need some sort of python lib for that?

**Comment by dfirfpi** [comment]
Never got such an error. Try a simple sqlite Python script to see if your host has everything working. It's not related to my script, closing the issue.
